services:
#================================
#Lancer postgresQl
#================================
  pg-insa:
    container_name: pg-insa
    image: pg-insa:latest
    command: postgres -c 'max_connections=200'
    networks:
      - insa-bridge
    hostname: pg-insa
    restart: always
    ports:
      - "5432:5432"
    environment:
      - TZ=CET
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=insa
      - POSTGRES_HOST_AUTH_METHOD=trust
      # ne pas oublier de parameter le volume de postgresql sur disque lvm
    volumes:
      - ./pgdata:/var/lib/postgresql/data

#================================
#Lancer le service ws template
#================================
  ws-template:
    depends_on:
      - pg-insa
    container_name: ws-template
    image: ws_services_template:latest
    networks:
      - insa-bridge
    hostname: ws-template
    restart: always
    ports:
      - "8800:8800"

#================================
#Lancer Kafka
#================================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1    

#renommer le r√©seau par defaut des services
networks:
    insa-bridge:
      name: insa-bridge
